# Generated by Django 6.0.6 on 2026-06-11 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('o', 'Outro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Cartão de Crédito'), (2, 'Cartão de Débito'), (3, 'Pix')], default=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('d', 'Disponível'), ('r', 'Reservado'), ('a', 'Agendado')], default='d', max_length=1)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.IntegerField(choices=[(1, 'Criança'), (2, 'Adulto'), (3, 'Casal')])),
                ('link_sala', models.URLField(blank=True, null=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('realizada', models.BooleanField(default=False)),
                ('presencial', models.BooleanField(default=True)),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='main.horario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.paciente')),
                ('pagamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crp', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('especialidades', models.ManyToManyField(to='main.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='PrecoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.IntegerField(choices=[(1, 'Criança'), (2, 'Adulto'), (3, 'Casal')])),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psicologo')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psicologo'),
        ),
    ]
