# Generated by Django 6.0.6 on 2026-06-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='confirmada',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='realizada',
        ),
        migrations.AddField(
            model_name='consulta',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Agendada'), (2, 'Confirmada'), (3, 'Realizada'), (9, 'Cancelada')], default=0),
        ),
    ]
