# Generated by Django 6.0.6 on 2026-06-26 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_consulta_confirmada_remove_consulta_realizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.horario'),
        ),
    ]
